### PR TITLE
Eliminated infinite loop when writing IIS LP to file

### LINKED ISSUE #2635: Highs_getIis segfaults
Am I calling something wrong?

```Julia
julia> using HiGHS

julia> unsafe_string(Highs_version())
"1.12.0"

julia> highs = Highs_create()
Ptr{Nothing}(0x000000013f53b800)

julia> Highs_readModel(highs, "/Users/odow/git/jump-dev/MathOptIIS/test/small.lp.gz")
Running HiGHS 1.12.0 (git hash: 755a8e027): Copyright (c) 2025 HiGHS under MIT licence terms
0

julia> m, n = Highs_getNumCol(highs), Highs_getNumRow(highs)
(396, 936)

julia> iis_num_col, iis_num_row = Ref{Cint}(m), Ref{Cint}(n)
(Base.RefValue{Int32}(396), Base.RefValue{Int32}(936))

julia> col_index, col_bound, col_status = zeros(Cint, m), zeros(Cint, m), zeros(Cint, m)
(Int32[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], Int32[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], Int32[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

julia> row_index, row_bound, row_status = zeros(Cint, n), zeros(Cint, n), zeros(Cint, n)
(Int32[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], Int32[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], Int32[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

julia> Highs_getIis(
           highs,
           iis_num_col,
           iis_num_row,
           col_index,
           row_index,
           col_bound,
           row_bound,
           col_status,
           row_status,
       )

[9037] signal 11 (2): Segmentation fault: 11
in expression starting at REPL[18]:1
Highs_getIis at /Users/odow/.julia/artifacts/927a651cf0aaaed9262d8ed83c6f9941840a837a/lib/libhighs.1.12.dylib (unknown line)
```

[small.lp.gz](https://github.com/user-attachments/files/23321807/small.lp.gz)

Same with the C code:

```c
#include <stdlib.h>
#include "interfaces/highs_c_api.h"

int main() {
    void* highs = Highs_create();
    int ret = Highs_readModel(highs, "small.lp.gz");
    HighsInt m = Highs_getNumCol(highs);
    HighsInt n = Highs_getNumRow(highs);
    HighsInt iis_num_col = 0;
    HighsInt iis_num_row = 0;
    HighsInt* col_index = (HighsInt*)malloc(sizeof(HighsInt) * m);
    HighsInt* row_index = (HighsInt*)malloc(sizeof(HighsInt) * n);
    HighsInt* col_bound = (HighsInt*)malloc(sizeof(HighsInt) * m);
    HighsInt* row_bound = (HighsInt*)malloc(sizeof(HighsInt) * n);
    HighsInt* col_status = (HighsInt*)malloc(sizeof(HighsInt) * m);
    HighsInt* row_status = (HighsInt*)malloc(sizeof(HighsInt) * n);
    ret = Highs_getIis(
        highs,
        &iis_num_col,
        &iis_num_row,
        col_index,
        row_index,
        col_bound,
        row_bound,
        col_status,
        row_status);
    Highs_destroy(highs);
    return 0;
}
```

### PR DESCRIPTION
**Pull request by jajhall**
Checking of (I)IS LP now done with `Highs::optimizeModel()`, eliminating infinite loop.

This will close #2635

### CODE REVIEW

**Comment by jajhall** [comment]
Closes #2635

**Comment by jajhall** [comment]
Once #2740 is pushed, this will look less scary

**Comment by jajhall** [comment]
It would be good to have your views on this, @haman80

**Review by Opt-Mucca — APPROVED** [review]
Looks good! Good idea adding a test too.

File: highs/lp_data/HighsInterface.cpp [hunk 1]
```diff
@@ -1925,9 +1925,10 @@ HighsStatus Highs::getIisInterface() {
   // light strategy
   if (options_.iis_strategy == kIisStrategyLight)
     return this->getIisInterfaceReturn(HighsStatus::kOk);
-  const bool ray_option =
+  bool ray_option =
       // kIisStrategyFromRay & options.iis_strategy;
       false;
+  const bool lp_option = kIisStrategyFromLp & options_.iis_strategy;
```
Comment (haman80) [inline highs/lp_data/HighsInterface.cpp:1931]: @jajhall If strategy is set to kIisStrategyIrreducible, lp_option will evaluate to false and we end up with an early exit.

**Comment by haman80** [comment]
@jajhall Thank you for the fix. I had a comment regarding the use of lp_option.

File: highs/lp_data/HighsInterface.cpp (hunk 1 above)
Comment (jajhall) [reply highs/lp_data/HighsInterface.cpp:1931]: Indeed, I think the better interpretation is that if the `kIisStrategyIrreducible` bit is set, then the IS is obtained from the  ray (if that bit is set - and the code works, which it doesn't at present) or the whole LP, regardless of whether  the `kIisStrategyLp` bit is set
